---
# Fix user setup for packer user

#  lock password to avoid password logins

- name: Lock packer user password to prevent password reset or login
  ansible.builtin.user:
    name: packer
    password: '*'

#  update authorized keys from @sdake and @rstarmer

- name: Set authorized keys for packer user - sdake
  ansible.posix.authorized_key:
    user: packer
    state: present
    key: "{{ lookup('url', 'https://github.com/sdake.keys', split_lines=False) }}"

- name: Set authorized keys for packer user - rstarmer
  ansible.posix.authorized_key:
    user: packer
    state: present
    key: "{{ lookup('url', 'https://github.com/rstarmer.keys', split_lines=False) }}"

# Update apt package cache and installed packages to latest versions

- name: update apt packages
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true
